        var percent = {
          'supplies': '',
          'money': '',
          'medals': '',
          'strategy_points': '',
          'special_goods': '',
          'random_goods': '',
          'previous_era_goods': '',
          'penal_unit': '',
          'clan_goods': '',
          'totem_drop': '%',
          'support_boost': '',
          'supplies_boost': '%',
          'spoils_of_war': '%',
          'quest_boost': '%',
          'population': '',
          'plunder_repel': '%',
          'plunder_goods': '',
          'plunder_and_pillage': '%',
          'money_boost': '%',
          'missile_launch': '%',
          'military_boost': '%',
          'helping_hands': '%',
          'happiness': '',
          'first_strike': '%',
          'fierce_resistance': '%',
          'double_collection': '%',
          'diplomatic_gifts': '%',
          'critical_hit_chance': '%',
          'contribution_boost': '%',
          'aid_goods': '',
          'aid_boost': '%',
          'advanced_tactics': '%'
        }
        var trials = {
          'supplies': false,
          'money': false,
          'medals': false,
          'strategy_points': false,
          'special_goods': false,
          'random_goods': false,
          'previous_era_goods': false,
          'penal_unit': false,
          'clan_goods': false,
          'totem_drop': false,
          'support_boost': false,
          'supplies_boost': false,
          'spoils_of_war': true,
          'quest_boost': false,
          'population': false,
          'plunder_repel': true,
          'plunder_goods': true,
          'plunder_and_pillage': false,
          'money_boost': false,
          'missile_launch': true,
          'military_boost': false,
          'helping_hands': true,
          'happiness': false,
          'first_strike': true,
          'fierce_resistance': false,
          'double_collection': true,
          'diplomatic_gifts': true,
          'critical_hit_chance': false,
          'contribution_boost': false,
          'aid_goods': true,
          'aid_boost': false,
          'advanced_tactics': false
        }
        var headers = {
          'supplies': 'Supplies<br />[[File:GBsupplies.png|20px|link=]]',
          'money': 'Coins<br />[[File:GBmoney.png|20px|link=]]',
          'medals': 'Medals<br />[[File:GBmedals.png|20px|link=]]',
          'strategy_points': 'FP<br />[[File:GBstrategy_points.png|20px|link=]]',
          'special_goods': 'Special<br />Goods<br /><br />[[File:GBspecial_goods.png|20px|link=]]',
          'random_goods': 'Goods<br /><br />[[File:GBrandom_goods.png|20px|link=]]',
          'previous_era_goods': 'Prev. <br />Goods<br />[[File:GBprevious_era_goods.png|20px|link=]]',
          'penal_unit': 'Units<br />[[File:GBpenal_unit.png|20px|link=]]',
          'clan_goods': 'Guild<br />Goods<br />[[File:GBclan_goods.png|20px|link=]]',
          'totem_drop': 'Relic<br />Chance<br />[[File:GBtotem_drop.png|20px|link=]]',
          'support_boost': 'Guild Support<br />Pool<br />[[File:GBsupport_boost.png|20px|link=]]',
          'supplies_boost': 'Boost<br />[[File:GBsupplies_boost.png|20px|link=]]',
          'spoils_of_war': 'Spoils<br />of War<br />[[File:GBspoils_of_war.png|20px|link=]]',
          'quest_boost': 'Quest Reward<br />Boost<br />[[File:GBquest_boost.png|20px|link=]]',
          'population': 'Population<br />[[File:GBpopulation.png|20px|link=]]',
          'plunder_repel': 'Plunder<br />Repel<br />[[File:GBplunder_repel.png|20px|link=]]',
          'plunder_goods': 'Plunder<br />Goods<br />[[File:GBplunder_goods.png|20px|link=]]',
          'plunder_and_pillage': 'Double<br />Plunder<br />[[File:GBplunder_and_pillage.png|20px|link=]]',
          'money_boost': 'Boost<br />[[File:CoinBoost.png|20px|link=]]',
          'missile_launch': 'Missile <br />Launch<br />[[File:GBmissile_launch.png|20px|link=]]',
          'military_boost': 'Attack<br />Boost<br />[[File:GBmilitary_boost.png|20px|link=]]',
          'helping_hands': 'Helping<br />Hands<br />[[File:GBhelping_hands.png|20px|link=]]',
          'happiness': 'Happiness<br />[[File:GBhappiness.png|20px|link=]]',
          'first_strike': 'First<br />Strike<br />[[File:GBfirst_strike.png|20px|link=]]',
          'fierce_resistance': 'Defense<br />Boost<br />[[File:GBfierce_resistance.png|20px|link=]]',
          'double_collection': 'Double<br />Collection<br />[[File:GBdouble_collection.png|20px|link=]]',
          'diplomatic_gifts': 'Diplomatic<br />Gifts<br />[[File:GBdiplomatic_gifts.png|20px|link=]]',
          'critical_hit_chance': 'Critical <br />Hit Chance<br />[[File:GBcritical_hit_chance.png|20px|link=]]',
          'contribution_boost': 'Contrib. <br />Reward Boost<br />[[File:GBcontribution_boost.png|20px|link=]]',
          'aid_goods': 'Aid Goods<br />[[File:GBaid_goods.png|20px|link=]]',
          'aid_boost': 'Aid Blueprint <br />Chance Boost<br />[[File:GBaid_boost.png|20px|link=]]',
          'advanced_tactics': 'Advanced<br />Tactics<br />[[File:GBadvanced_tactics.png|20px|link=]]',
          'hps': 'Eff.<br />{{IHAP}}/{{ISIZ}}',
          'pps': 'Eff.<br />{{IPOP}}/{{ISIZ}}',
          'gr': 'Uncom. <br />Relic<br />[[file:gold relic uncommon.png|link=|20px]]',
          'jr': 'Rare <br />Relic<br />[[file:jade relic rare.png|link=|20px]]',
          'sr': 'Com. <br />Relic<br />[[file:silver relic common.png|link=|20px]]',

        }
        var size = {
          'X_AllAge_EasterBonus4': 9,
          'X_AllAge_Expedition': 36,
          'X_AllAge_Galata': 9,
          'X_AllAge_Oracle': 9,
          'X_ArcticFuture_Landmark1': 24,
          'X_ArcticFuture_Landmark2': 49,
          'X_ArcticFuture_Landmark3': 30,
          'X_BronzeAge_Landmark1': 16,
          'X_BronzeAge_Landmark2': 6,
          'X_ColonialAge_Landmark1': 25,
          'X_ColonialAge_Landmark2': 49,
          'X_ContemporaryEra_Landmark1': 36,
          'X_ContemporaryEra_Landmark2': 36,
          'X_EarlyMiddleAge_Landmark1': 42,
          'X_EarlyMiddleAge_Landmark2': 24,
          'X_FutureEra_Landmark1': 35,
          'X_FutureEra_Landmark2': 36,
          'X_HighMiddleAge_Landmark1': 36,
          'X_HighMiddleAge_Landmark3': 24,
          'X_IndustrialAge_Landmark1': 42,
          'X_IndustrialAge_Landmark2': 35,
          'X_IronAge_Landmark1': 42,
          'X_IronAge_Landmark2': 16,
          'X_LateMiddleAge_Landmark1': 25,
          'X_LateMiddleAge_Landmark3': 25,
          'X_ModernEra_Landmark1': 30,
          'X_ModernEra_Landmark2': 42,
          'X_OceanicFuture_Landmark1': 42,
          'X_OceanicFuture_Landmark2': 25,
          'X_OceanicFuture_Landmark3': 35,
          'X_PostModernEra_Landmark1': 20,
          'X_PostModernEra_Landmark2': 42,
          'X_ProgressiveEra_Landmark1': 70,
          'X_ProgressiveEra_Landmark2': 30,
          'X_SpaceAgeAsteroidBelt_Landmark1': 28,
          'X_SpaceAgeMars_Landmark1': 25,
          'X_SpaceAgeMars_Landmark2': 25,
          'X_TomorrowEra_Landmark1': 28,
          'X_TomorrowEra_Landmark2': 30,
          'X_VirtualFuture_Landmark1': 24,
          'X_VirtualFuture_Landmark2': 36
        }